apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: minha-app
  template:
    metadata:
      labels:
        app: minha-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80